/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.quereesse;

import br.com.quereesse.cadProduto.Produto;
import br.com.quereesse.cadProduto.ProdutoDAOImpl;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vsued
 */
public class ConsultaProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaProduto
     */
    ArrayList <Produto> produtos;
    DefaultTableModel modeloTabela;

    public ConsultaProduto() {
        initComponents();
        modeloTabela = (DefaultTableModel) tabela.getModel();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScroll = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jbuttonProdConsulta = new javax.swing.JButton();
        jbuttonProdCancela = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Avaliação", "Especificação", "Modelo", " Comentário"
            }
        ));
        tabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScroll.setViewportView(tabela);

        jbuttonProdConsulta.setText("Consultar");
        jbuttonProdConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonProdConsultaActionPerformed(evt);
            }
        });

        jbuttonProdCancela.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jbuttonProdConsulta)
                .addGap(180, 180, 180)
                .addComponent(jbuttonProdCancela)
                .addGap(27, 27, 27))
            .addComponent(jScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonProdConsulta)
                    .addComponent(jbuttonProdCancela))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonProdConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonProdConsultaActionPerformed
        modeloTabela.setNumRows(0);

        ProdutoDAOImpl crud = new ProdutoDAOImpl();
        produtos = crud.consulta();
        for(Produto produto: produtos){ 
            Object linha[] = new Object[5];
            linha[0] = produto.getNomeProduto();
            linha[1] = produto.getAvaliacao();
            linha[2] = produto.getEspecificacao();
            linha[3] = produto.getModelo();
            linha[4] = produto.getDscComentario();
            modeloTabela.addRow(linha);
            System.out.println(produto.getDscComentario());
        }
        
    }//GEN-LAST:event_jbuttonProdConsultaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScroll;
    private javax.swing.JButton jbuttonProdCancela;
    private javax.swing.JButton jbuttonProdConsulta;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
