version: "3"
services:
  workerapiqueroesse:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always  
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
    volumes:
      - .:/app
    networks:
      - queroesse-network     
            
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5673:5672"
      - "15672:15672"
    networks:
      - queroesse-network    

  workerqueroesse:
    build:
      context: .
    hostname: workerqueroesse
    entrypoint: celery
    command: -A worker worker --loglevel=info
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit
    networks:
      - queroesse-network      

networks: 
  queroesse-network:
    driver: bridge